# Generated by Django 4.0.5 on 2022-06-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_varified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('avtar', models.ImageField(default='images/avtar/User-Profile.png', upload_to='images/avtar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
