# Generated by Django 4.0.5 on 2022-06-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='addressof',
            new_name='address',
        ),
    ]
